# Autogenerated wrapper script for ocl_icd_jll for x86_64-w64-mingw32
export libocl_icd, ocl_icd_h

using dlfcn_win32_jll
JLLWrappers.@generate_wrapper_header("ocl_icd")
JLLWrappers.@declare_library_product(libocl_icd, "libOpenCL-1.dll")
JLLWrappers.@declare_file_product(ocl_icd_h)
function __init__()
    JLLWrappers.@generate_init_header(dlfcn_win32_jll)
    JLLWrappers.@init_library_product(
        libocl_icd,
        "bin\\libOpenCL-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        ocl_icd_h,
        "include\\ocl_icd.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
